[package]
name = "bdir-core"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
hex = "0.4.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.149"
xxhash-rust = { version = "0.8.15", features = ["xxh3"] }
sha2 = "0.10"
