[package]
name = "bdir-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "bdir"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde_json = "1"
bdir-core = { path = "../bdir-core" }
bdir-editpacket = { path = "../bdir-editpacket" }
anyhow = "1"
